version: '2.0'

services:
    mongo:
        image: mongo
        ports:
            - 27017:27017
    rest:
        build:
            context: ..
            dockerfile: ./dev/Dockerfile
        environment:
            - PREPI_ENV=dev
            - NODE_ENV=dev
        volumes:
            - ..:/var/app/
            - /var/app/node_modules

        ports:
            - 8080:8080

        command: sh -c "sleep 5 && npm i && npm run dev"

        depends_on:
            - mongo
